// Generated by CoffeeScript 1.6.3
(function() {
  var fs, mkdirp, path;

  fs = require("fs");

  path = require("path");

  mkdirp = require("mkdirp");

  exports.browseImage = function(request, response, next) {};

  exports.uploadImage = function(request, response, next) {
    var ckEditorFuncNum, file, userDir;
    log("upload start");
    /*
    unless request.user
    return response.send
    status: "forbidden"
    */

    ckEditorFuncNum = request.param("CKEditorFuncNum");
    file = request.files && request.files.upload;
    if (!file) {
      return response.send({
        status: "failed",
        message: "no file"
      });
    }
    userDir = config.uploadDir;
    return mkdirp(userDir, function(error) {
      var filename, savepath;
      if (error) {
        return next(error);
      }
      filename = "" + (Date.now()) + "_" + file.name;
      savepath = path.resolve(path.join(userDir, filename));
      if (savepath.indexOf(path.resolve(userDir)) !== 0) {
        return response.send({
          status: "forbidden"
        });
      }
      return fs.rename(file.path, savepath, function(error) {
        var url;
        if (error) {
          return next(error);
        }
        url = "/upload/" + (encodeURIComponent(filename));
        return response.send("<script>\n    document.domain = '127.0.0.1.xip.io';\n    window.parent.CKEDITOR.tools.callFunction('" + ckEditorFuncNum + "','" + url + "','Success');\n</script>");
      });
    });
  };

}).call(this);
